public  class PrimiteDataType {
  public void printBasicDataType()  {
      //method body
      string batchName = 'Falcon8';
      integer totalCandidates = 40;
      boolean isAdminComleted = true;
      system.debug(batchName);
      system.debug(totalCandidates);
      system.debug(isAdminComleted);

string batchDescription = batchName + 'are the best.';
system.debug(batchDescription);
  }
    
}
